language: java
jdk:
- openjdk8

addons:
  firefox: "55.0.3"

before_install:
  - pip install -r robot/requirements.txt

install:
  - ./gradlew bootRepackage

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar zxvf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script:
  - ./gradlew test # Unit tests
  - "java -jar build/libs/demo-0.0.1-SNAPSHOT.jar --demo.mock=true &> /dev/null &"
  - sleep 20 # Wait for spring to boot
  - pybot robot

before_deploy:
  - openssl aes-256-cbc -K $encrypted_c4f2ba029423_key -iv $encrypted_c4f2ba029423_iv
    -in orders.enc -out orders -d
  - chmod 600 orders

deploy:
  - provider: script
    skip_cleanup: true
    script: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i orders build/libs/demo-0.0.1-SNAPSHOT.jar ubuntu@ubuntu@orders.arcada.nitor.zone:app.jar
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt -i orders ubuntu@orders.arcada.nitor.zone /home/ubuntu/restartApp.sh
    on:
      branch: master