language: java
jdk:
- openjdk8
addons:
  firefox: 55.0.3

before_install:
    - sudo pip install -r robot/requirements.txt
    - chmod +x gradlew
install:
    - "./gradlew bootRepackage"
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
    - mkdir geckodriver
    - tar zxvf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
script:
    - java -jar build/libs/orders-0.0.1-SNAPSHOT.jar &> /dev/null &
    - sleep 20
before_deploy:
    - openssl aes-256-cbc -K $encrypted_2390d7ff4426_key -iv $encrypted_2390d7ff4426_iv 
     -in sshOrders.enc -out sshOrders -d
    - chmod 600 sshOrders 
deploy:
    - provider: script
      skip_cleanup: true
      script: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i sshOrders build/libs/orders-0.0.1-SNAPSHOT.jar ubuntu@orders.arcada.nitor.zone:app.jar
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt -i sshOrders ubuntu@orders.arcada.nitor.zone /home/ubuntu/restartApp.sh
      on:
        branch: master
