spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.55/
    username: root
    password: Saku17arc
jpa:
  hibernate.ddl-auto: create
  generate-ddl: true
  show-sql: true